- name: Loop
  hosts: all
  tasks:
    - name: Fruit Name
      ansible.builtin.debug:
        msg: Fruit Name == {{ item }}

      loop:
          -  banana
          -  apple

    - name: Fruit Name with Quantity
      ansible.builtin.debug:
        msg: Fruit Name == {"{ item.name}, {item.Qty}"}
      loop:
        -  { name: banana, Qty: 100 }
        -  { name: apple, Qty: 200 }
